.TH pspdftool 1 "2007-09-18"
.SH NAME
pspdftool -  tool for prepress preparation of PDF and PostScript documents

.SH SYNOPSIS
.B pspdftool
[
.B \-f\fIfile\fR name
] [
.B \-h\fIhelp\fR
]
[
.I commands
]
[
.I infile
[
.I outfile
] ]


.SH DESCRIPTION
.I pspdftool
rearranges pages from a supported document, creating a new file.
Supported documents are PostScript and PDF.
The input PostScript file should follow the Adobe Document Structuring
Conventions.

.I pspdftool
can be used to perform a large number of arbitrary re-arrangements of
Documents, including arranging for printing 2-up, 4-up, booklets, reversing,
selecting front or back sides of documents, scaling, etc.
.PP
.I commands
follow the syntax:
.RS
.TP 12
.I commands
.I = command ... command
.TP
.I command
.I = name(arg,name=arg2 ...){page selection}
.TP
. I arg: identifier, string, number, real number
.TP
page selection
.TP
.I number
page form begin of the list
.TP
.I -number
page from end of the list
.TP
.I number..number
page range from begin of the list
.TP
.I -number..number
page range from end of the list
.TP
.I $
end page in list
.RE
.sp
.| command

list of supported commands

Commands for working with documents:

.RS
.TP 12
.B read
.I (name=<str>)

append file at the end of list
.TP
.B write
.I (name=<str>)

save list to file

.RE
Commands for working with pages selections:
.RS
.TP 12
.B modulo
.I (pages, half, round){page_ranges}
.TP
.B book
.TP
.B select{page_ranges}
.TP
.B apply{page_ranges}
.TP
.B new{page_ranges}

add new page at the end of list

.TP
.B del


delete list

.TP
.B scale
.I (scale=<real>)

scale pages in the list

.RE
Command for pages' content transform:
.RS
.TP 12
.B scaleto
.I (paper, top, right, bottom, left)

fit page to paper

.TP
.B scaleto2
.I (x, y, top, right, bottom, left)
.TP
.B flip
.I (mode=<id>)

horizontal | vertical

.TP
.B number
.I (x, y, start, text, font, size)

add numbers to pages

.TP
.B crop
.I (paper)
.TP
.B crop2
.I (lx, ly, hx, hy)
.TP
.B paper
.I (paper)

sets paper size

.TP
.B paper2
.I (x,y)

sets papes size to exact size

.TP
.B orient 
.I (orient)

set text orientation the page landscape|portrait

.TP
.B nup
.I (x, y, dx, dy, orient, rotate, by_bbox, paper, frame, center)

If is set only x to some value n, then command puts n pages to one paper.
If is set x and y, then command puts x*y pages to one paper. X means number of columns and y means number of rows.
Paper is name of final paper size (e.g. a4,letter ...). Rotate will rotate each page before fitting.

.TP
.B merge

merge list to one page

.TP
.B text
.I (x, y, text, font, size)

write text to page

.TP
.B line 
.I (lx,ly,hx,hy,width)

draw line to page

.TP
.B rotate
.I (angle)

rotate page
.TP
.B move
.I(x, y)
.TP
.B matrix
.I(a,b,c,d,e,f)


transform by matrix

.RE
Misc commands:
.RS
.TP 12
.B bbox


recalculate bbox on each page by GhostScript

.TP
.B cmarks(by_bbox=1)

add printing marks, if by_bbox is 0 then printing marks are added by paper size, 
else they are added by bounding box

.TP
.B duplex
.I (long-edge)

aranges pages for duplex printing

.TP
.B norm
.I (center,scale,l_bbox,g_bbox)

normalize  pages in list on the same size

.RE
.sp


.RE
.SH OPTIONS
.TP
.B "\-h  \-\-help"
display help message and exit
.TP
.B "\-f \-\-file"
read commands from file

.SH EXAMPLE
This section contains some sample re-arrangements. To put two pages on one
sheet (of A4 paper):
.sp
.ce
.B nup(2, paper=a4)
.sp
or:
.sp
.ce
.B nup(1,2, paper=a4,rotate=90)
.sp
To re-arrange pages for printing 2-up booklets, use
.sp
.ce
.B book nup(2, paper=a4)
.sp
select first five pages and last one from document
.sp
.ce
.B select{1..5 -1}
.sp
delete last page from document
.sp
.ce
.B select{$..1}
.sp
reverse page in list
.sp
.ce
.B apply{-1 del}
.sp
reverse pages in document
.sp
.ce
.B modulo(2){-1}
.sp
select even pages form document
.sp
.ce
.B modulo(2){2}
.sp
fit page to a4
.sp
.ce
.B scaleto(a4)
.SH AUTHORS
Ales Snuparek <snuparek@atlas.cz>
.SH TRADEMARKS
.B PostScript
and
.B PDF
are  trademarks of Adobe Systems Incorporated.

.SH BUGS
.I Pdftool
does not accept all types of PDF and PostScript files.
Cannot cut two or more PostScript files together.


